version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./static-html:/usr/share/nginx/html
    ports:
      - "82:80"
    networks:
      - web_network
    
networks:
  web_network:
    name: nginx
    driver: bridge
